#!/bin/bash  
#Todd Houle 
#Partners Healthcare
#19June2014    
#revised 11Feb2015 Alexander Kaltsas
#To determine if connected time machine disk is encrypted. 

mountPath=`tmutil destinationinfo | grep "Mount Point" | awk -F ": " '{print $2}'`
if [ "$mountPath" == "" ]; then
    tmExists=`tmutil destinationinfo |grep "No destinations configured"| awk '{print $2 $3 $4}'`
    if [ "$tmExists" == "Nodestinationsconfigured." ]; then
        result="Backup Not Enabled"
    else
        result="Disk not available"
    fi
else
    disk=`df -h|grep "$mountPath"|awk '{print $1}'`
    result=`diskutil cs info $disk |grep "Conversion State" | awk '{print $3}'`
    if [ "$result" == ""  ] ; then
        result="Not Encrypted"
    fi
    if [ "$result" == "Converting"  ] ; then
    	result="Encrypting"
    fi
    if [ "$result" == "Complete"  ] ; then
    	result="Encrypted"
    fi
    
fi

echo "<result>$result</result>"
